name: Deploy PR previews

concurrency: preview-${{ github.ref }}

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - 'docs/**'

permissions:
  pull-requests: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rossjrw/pr-preview-action@v1
        with:
          preview-branch: master
          umbrella-dir: docs/pr-preview/
          action: auto
          source-dir: ./docs/
